// Generated by tools/digit_atlas.py: the damage-number atlases (public/ui/digits) and where each glyph sits.
// `w`/`h`: the atlas size; `top`/`base`: where the digit tops and baseline sit down a sprite; per glyph `x`/`w`: its
// rect in the atlas, `adv`: how far the next glyph moves along, `lead`: where its solid part starts.
export interface DigitGlyph { c: string; x: number; w: number; adv: number; lead: number }
export interface GlyphSet { file: string; w: number; h: number; top: number; base: number; space?: number; glyphs: DigitGlyph[] }
export type DigitKind = 'white' | 'crit' | 'heal' | 'hurt';
export const DIGIT_SETS: Record<DigitKind, GlyphSet> = {
  "white": {
    "file": "ui/digits/white.png",
    "w": 566,
    "h": 73,
    "top": 5.0,
    "base": 68.5,
    "glyphs": [
      {
        "c": "0",
        "x": 0,
        "w": 48,
        "adv": 43.0,
        "lead": 3.0
      },
      {
        "c": "1",
        "x": 50,
        "w": 34,
        "adv": 29.0,
        "lead": 3.0
      },
      {
        "c": "2",
        "x": 86,
        "w": 44,
        "adv": 40.0,
        "lead": 3.0
      },
      {
        "c": "3",
        "x": 132,
        "w": 46,
        "adv": 42.0,
        "lead": 3.0
      },
      {
        "c": "4",
        "x": 180,
        "w": 48,
        "adv": 43.5,
        "lead": 3.0
      },
      {
        "c": "5",
        "x": 230,
        "w": 46,
        "adv": 41.0,
        "lead": 3.0
      },
      {
        "c": "6",
        "x": 278,
        "w": 44,
        "adv": 40.0,
        "lead": 3.0
      },
      {
        "c": "7",
        "x": 324,
        "w": 52,
        "adv": 48.0,
        "lead": 3.0
      },
      {
        "c": "8",
        "x": 378,
        "w": 48,
        "adv": 43.0,
        "lead": 3.0
      },
      {
        "c": "9",
        "x": 428,
        "w": 44,
        "adv": 39.5,
        "lead": 3.0
      },
      {
        "c": "+",
        "x": 474,
        "w": 46,
        "adv": 42.0,
        "lead": 3.0
      },
      {
        "c": "-",
        "x": 522,
        "w": 42,
        "adv": 37.0,
        "lead": 3.0
      }
    ]
  },
  "crit": {
    "file": "ui/digits/crit.png",
    "w": 756,
    "h": 90,
    "top": 13.5,
    "base": 76.5,
    "glyphs": [
      {
        "c": "0",
        "x": 0,
        "w": 64,
        "adv": 43.0,
        "lead": 11.0
      },
      {
        "c": "1",
        "x": 66,
        "w": 52,
        "adv": 31.0,
        "lead": 11.0
      },
      {
        "c": "2",
        "x": 120,
        "w": 60,
        "adv": 40.0,
        "lead": 11.0
      },
      {
        "c": "3",
        "x": 182,
        "w": 64,
        "adv": 44.0,
        "lead": 11.0
      },
      {
        "c": "4",
        "x": 248,
        "w": 64,
        "adv": 43.0,
        "lead": 11.0
      },
      {
        "c": "5",
        "x": 314,
        "w": 60,
        "adv": 40.0,
        "lead": 11.0
      },
      {
        "c": "6",
        "x": 376,
        "w": 61,
        "adv": 40.5,
        "lead": 11.0
      },
      {
        "c": "7",
        "x": 439,
        "w": 62,
        "adv": 42.0,
        "lead": 11.0
      },
      {
        "c": "8",
        "x": 503,
        "w": 64,
        "adv": 43.0,
        "lead": 11.0
      },
      {
        "c": "9",
        "x": 569,
        "w": 60,
        "adv": 39.5,
        "lead": 11.0
      },
      {
        "c": "+",
        "x": 631,
        "w": 64,
        "adv": 44.0,
        "lead": 11.0
      },
      {
        "c": "-",
        "x": 697,
        "w": 57,
        "adv": 36.5,
        "lead": 11.0
      }
    ]
  },
  "heal": {
    "file": "ui/digits/heal.png",
    "w": 617,
    "h": 78,
    "top": 5.0,
    "base": 72.0,
    "glyphs": [
      {
        "c": "0",
        "x": 0,
        "w": 53,
        "adv": 48.5,
        "lead": 3.0
      },
      {
        "c": "1",
        "x": 55,
        "w": 38,
        "adv": 33.0,
        "lead": 3.0
      },
      {
        "c": "2",
        "x": 95,
        "w": 50,
        "adv": 45.0,
        "lead": 3.0
      },
      {
        "c": "3",
        "x": 147,
        "w": 51,
        "adv": 46.5,
        "lead": 3.0
      },
      {
        "c": "4",
        "x": 200,
        "w": 52,
        "adv": 48.0,
        "lead": 3.0
      },
      {
        "c": "5",
        "x": 254,
        "w": 50,
        "adv": 45.0,
        "lead": 3.0
      },
      {
        "c": "6",
        "x": 306,
        "w": 50,
        "adv": 45.0,
        "lead": 3.0
      },
      {
        "c": "7",
        "x": 358,
        "w": 52,
        "adv": 48.0,
        "lead": 3.0
      },
      {
        "c": "8",
        "x": 412,
        "w": 52,
        "adv": 47.0,
        "lead": 3.0
      },
      {
        "c": "9",
        "x": 466,
        "w": 49,
        "adv": 44.5,
        "lead": 3.0
      },
      {
        "c": "+",
        "x": 517,
        "w": 50,
        "adv": 46.0,
        "lead": 3.0
      },
      {
        "c": "-",
        "x": 569,
        "w": 46,
        "adv": 42.0,
        "lead": 3.0
      }
    ]
  },
  "hurt": {
    "file": "ui/digits/hurt.png",
    "w": 566,
    "h": 73,
    "top": 5.0,
    "base": 68.5,
    "glyphs": [
      {
        "c": "0",
        "x": 0,
        "w": 48,
        "adv": 43.0,
        "lead": 3.0
      },
      {
        "c": "1",
        "x": 50,
        "w": 34,
        "adv": 29.0,
        "lead": 3.0
      },
      {
        "c": "2",
        "x": 86,
        "w": 44,
        "adv": 40.0,
        "lead": 3.0
      },
      {
        "c": "3",
        "x": 132,
        "w": 46,
        "adv": 42.0,
        "lead": 3.0
      },
      {
        "c": "4",
        "x": 180,
        "w": 48,
        "adv": 43.5,
        "lead": 3.0
      },
      {
        "c": "5",
        "x": 230,
        "w": 46,
        "adv": 41.0,
        "lead": 3.0
      },
      {
        "c": "6",
        "x": 278,
        "w": 44,
        "adv": 40.0,
        "lead": 3.0
      },
      {
        "c": "7",
        "x": 324,
        "w": 52,
        "adv": 48.0,
        "lead": 3.0
      },
      {
        "c": "8",
        "x": 378,
        "w": 48,
        "adv": 43.0,
        "lead": 3.0
      },
      {
        "c": "9",
        "x": 428,
        "w": 44,
        "adv": 39.5,
        "lead": 3.0
      },
      {
        "c": "+",
        "x": 474,
        "w": 46,
        "adv": 42.0,
        "lead": 3.0
      },
      {
        "c": "-",
        "x": 522,
        "w": 42,
        "adv": 37.0,
        "lead": 3.0
      }
    ]
  }
};
